// <auto-generated />
using System;
using FunBooksAndVideos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunBooksAndVideos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260919173823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("PurchaseOrderIds");

            modelBuilder.Entity("FunBooksAndVideos.Domain.Customers.Customer", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Orders.PurchaseOrder", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("PurchaseOrders", (string)null);
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Products.Product", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasDiscriminator<string>("Kind").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Shipping.ShippingSlip", b =>
                {
                    b.Property<long>("PurchaseOrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("PurchaseOrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ShippingSlips", (string)null);
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Products.DigitalProduct", b =>
                {
                    b.HasBaseType("FunBooksAndVideos.Domain.Products.Product");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Category");

                    b.HasDiscriminator().HasValue("Digital");
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Products.MembershipProduct", b =>
                {
                    b.HasBaseType("FunBooksAndVideos.Domain.Products.Product");

                    b.Property<string>("GrantedCategories")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue("Membership");
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Products.PhysicalProduct", b =>
                {
                    b.HasBaseType("FunBooksAndVideos.Domain.Products.Product");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Category");

                    b.HasDiscriminator().HasValue("Physical");
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Customers.Customer", b =>
                {
                    b.OwnsMany("FunBooksAndVideos.Domain.Customers.Membership", "Memberships", b1 =>
                        {
                            b1.Property<long>("CustomerId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTimeOffset>("ActivatedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("GrantedCategories")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<long>("ProductId")
                                .HasColumnType("bigint");

                            b1.HasKey("CustomerId", "Id");

                            b1.HasIndex("ProductId");

                            b1.HasIndex("CustomerId", "ProductId")
                                .IsUnique();

                            b1.ToTable("Memberships", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasOne("FunBooksAndVideos.Domain.Products.Product", null)
                                .WithMany()
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Orders.PurchaseOrder", b =>
                {
                    b.HasOne("FunBooksAndVideos.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("FunBooksAndVideos.Domain.Orders.PurchaseOrderItem", "Items", b1 =>
                        {
                            b1.Property<long>("PurchaseOrderId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Price")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<long>("ProductId")
                                .HasColumnType("bigint");

                            b1.HasKey("PurchaseOrderId", "Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("PurchaseOrderItems", (string)null);

                            b1.HasOne("FunBooksAndVideos.Domain.Products.Product", "Product")
                                .WithMany()
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");

                            b1.Navigation("Product");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Shipping.ShippingSlip", b =>
                {
                    b.HasOne("FunBooksAndVideos.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FunBooksAndVideos.Domain.Orders.PurchaseOrder", null)
                        .WithOne()
                        .HasForeignKey("FunBooksAndVideos.Domain.Shipping.ShippingSlip", "PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("FunBooksAndVideos.Domain.Shipping.ShippingSlipItem", "Items", b1 =>
                        {
                            b1.Property<long>("PurchaseOrderId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<long>("ProductId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("PurchaseOrderId", "Id");

                            b1.ToTable("ShippingSlipItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
